CREATE TABLE IF NOT EXISTS companies (
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(160) NOT NULL,
  registration_number VARCHAR(80) NULL,
  vat_registration_number VARCHAR(80) NULL,
  address VARCHAR(500) NULL,
  email VARCHAR(191) NULL,
  telephone VARCHAR(120) NULL,
  status ENUM('ACTIVE', 'INACTIVE', 'ARCHIVED', 'DELETED') NOT NULL DEFAULT 'ACTIVE',
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  created_by_id INT NULL,
  updated_by_id INT NULL,
  deleted_at DATETIME(3) NULL,
  deleted_by_id INT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY companies_name_key (name),
  KEY companies_status_idx (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS offices (
  id INT NOT NULL AUTO_INCREMENT,
  company_id INT NOT NULL,
  code VARCHAR(40) NOT NULL,
  name VARCHAR(160) NOT NULL,
  office_type ENUM('MAIN', 'BRANCH') NOT NULL,
  address VARCHAR(500) NULL,
  email VARCHAR(191) NULL,
  contact_person VARCHAR(160) NULL,
  telephone VARCHAR(120) NULL,
  status ENUM('ACTIVE', 'INACTIVE', 'ARCHIVED', 'DELETED') NOT NULL DEFAULT 'ACTIVE',
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  created_by_id INT NULL,
  updated_by_id INT NULL,
  deleted_at DATETIME(3) NULL,
  deleted_by_id INT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY offices_code_key (code),
  KEY offices_company_id_idx (company_id),
  KEY offices_office_type_idx (office_type),
  KEY offices_status_idx (status),
  CONSTRAINT offices_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS factories (
  id INT NOT NULL AUTO_INCREMENT,
  company_id INT NOT NULL,
  code VARCHAR(40) NOT NULL,
  name VARCHAR(160) NOT NULL,
  address VARCHAR(500) NULL,
  email VARCHAR(191) NULL,
  contact_person VARCHAR(160) NULL,
  telephone VARCHAR(120) NULL,
  status ENUM('ACTIVE', 'INACTIVE', 'ARCHIVED', 'DELETED') NOT NULL DEFAULT 'ACTIVE',
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  created_by_id INT NULL,
  updated_by_id INT NULL,
  deleted_at DATETIME(3) NULL,
  deleted_by_id INT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY factories_code_key (code),
  KEY factories_company_id_idx (company_id),
  KEY factories_status_idx (status),
  CONSTRAINT factories_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS warehouses (
  id INT NOT NULL AUTO_INCREMENT,
  company_id INT NOT NULL,
  office_id INT NULL,
  factory_id INT NULL,
  code VARCHAR(40) NOT NULL,
  name VARCHAR(160) NOT NULL,
  warehouse_type ENUM('MAIN', 'FACTORY_FINAL_PRODUCT', 'BRANCH') NOT NULL,
  address VARCHAR(500) NULL,
  email VARCHAR(191) NULL,
  contact_person VARCHAR(160) NULL,
  telephone VARCHAR(120) NULL,
  status ENUM('ACTIVE', 'INACTIVE', 'ARCHIVED', 'DELETED') NOT NULL DEFAULT 'ACTIVE',
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  created_by_id INT NULL,
  updated_by_id INT NULL,
  deleted_at DATETIME(3) NULL,
  deleted_by_id INT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY warehouses_code_key (code),
  KEY warehouses_company_id_idx (company_id),
  KEY warehouses_office_id_idx (office_id),
  KEY warehouses_factory_id_idx (factory_id),
  KEY warehouses_warehouse_type_idx (warehouse_type),
  KEY warehouses_status_idx (status),
  CONSTRAINT warehouses_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT warehouses_office_id_fkey FOREIGN KEY (office_id) REFERENCES offices(id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT warehouses_factory_id_fkey FOREIGN KEY (factory_id) REFERENCES factories(id) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS sales_reps (
  id INT NOT NULL AUTO_INCREMENT,
  office_id INT NOT NULL,
  user_id INT NULL,
  code VARCHAR(40) NOT NULL,
  name VARCHAR(160) NOT NULL,
  nic VARCHAR(80) NOT NULL,
  address VARCHAR(500) NULL,
  telephone VARCHAR(120) NULL,
  email VARCHAR(191) NULL,
  status ENUM('ACTIVE', 'INACTIVE', 'SUSPENDED', 'DELETED') NOT NULL DEFAULT 'ACTIVE',
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  created_by_id INT NULL,
  updated_by_id INT NULL,
  deleted_at DATETIME(3) NULL,
  deleted_by_id INT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY sales_reps_code_key (code),
  KEY sales_reps_office_id_idx (office_id),
  KEY sales_reps_user_id_idx (user_id),
  KEY sales_reps_status_idx (status),
  CONSTRAINT sales_reps_office_id_fkey FOREIGN KEY (office_id) REFERENCES offices(id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT sales_reps_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS customers (
  id INT NOT NULL AUTO_INCREMENT,
  office_id INT NOT NULL,
  sales_rep_id INT NULL,
  code VARCHAR(40) NOT NULL,
  customer_type ENUM('BUSINESS', 'INDIVIDUAL') NOT NULL,
  display_name VARCHAR(180) NOT NULL,
  registration_number VARCHAR(80) NULL,
  vat_registration_number VARCHAR(80) NULL,
  nic VARCHAR(80) NULL,
  address VARCHAR(500) NULL,
  telephone VARCHAR(120) NULL,
  contact_person VARCHAR(160) NULL,
  email VARCHAR(191) NULL,
  status ENUM('ACTIVE', 'INACTIVE', 'ARCHIVED', 'DELETED') NOT NULL DEFAULT 'ACTIVE',
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  created_by_id INT NULL,
  updated_by_id INT NULL,
  deleted_at DATETIME(3) NULL,
  deleted_by_id INT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY customers_code_key (code),
  KEY customers_office_id_idx (office_id),
  KEY customers_sales_rep_id_idx (sales_rep_id),
  KEY customers_customer_type_idx (customer_type),
  KEY customers_status_idx (status),
  CONSTRAINT customers_office_id_fkey FOREIGN KEY (office_id) REFERENCES offices(id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT customers_sales_rep_id_fkey FOREIGN KEY (sales_rep_id) REFERENCES sales_reps(id) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS customer_change_requests (
  id INT NOT NULL AUTO_INCREMENT,
  customer_id INT NOT NULL,
  requested_by_id INT NOT NULL,
  reviewed_by_id INT NULL,
  status ENUM('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED') NOT NULL DEFAULT 'PENDING',
  requested_changes JSON NOT NULL,
  reason VARCHAR(500) NULL,
  review_note VARCHAR(500) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  reviewed_at DATETIME(3) NULL,
  PRIMARY KEY (id),
  KEY customer_change_requests_customer_id_idx (customer_id),
  KEY customer_change_requests_requested_by_id_idx (requested_by_id),
  KEY customer_change_requests_reviewed_by_id_idx (reviewed_by_id),
  KEY customer_change_requests_status_idx (status),
  CONSTRAINT customer_change_requests_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT customer_change_requests_requested_by_id_fkey FOREIGN KEY (requested_by_id) REFERENCES users(id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT customer_change_requests_reviewed_by_id_fkey FOREIGN KEY (reviewed_by_id) REFERENCES users(id) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS customer_change_history (
  id INT NOT NULL AUTO_INCREMENT,
  customer_id INT NOT NULL,
  change_request_id INT NULL,
  changed_by_id INT NULL,
  old_values JSON NULL,
  new_values JSON NOT NULL,
  changed_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  KEY customer_change_history_customer_id_idx (customer_id),
  KEY customer_change_history_change_request_id_idx (change_request_id),
  KEY customer_change_history_changed_by_id_idx (changed_by_id),
  CONSTRAINT customer_change_history_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT customer_change_history_changed_by_id_fkey FOREIGN KEY (changed_by_id) REFERENCES users(id) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
