INSERT INTO permissions (code, name, module, description) VALUES
  ('dashboard.read', 'Read dashboard', 'dashboard', 'View operational dashboard summaries and pending action widgets'),
  ('reports.sales', 'View sales reports', 'reports', 'View sales summary and sales rep performance reports'),
  ('reports.collections', 'View collection reports', 'reports', 'View payment and collection summary reports'),
  ('reports.inventory', 'View inventory reports', 'reports', 'View inventory stock, low-stock, and stock value reports'),
  ('reports.delivery', 'View delivery reports', 'reports', 'View delivery performance reports'),
  ('reports.performance', 'View performance reports', 'reports', 'View target and commission performance reports'),
  ('system_config.read', 'Read system configuration', 'system_config', 'View system configuration settings'),
  ('system_config.update', 'Update system configuration', 'system_config', 'Create, update, and soft delete system configuration settings')
ON DUPLICATE KEY UPDATE
  name = VALUES(name),
  module = VALUES(module),
  description = VALUES(description);

INSERT IGNORE INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r
CROSS JOIN permissions p
WHERE r.code = 'SUPER_ADMIN';

INSERT IGNORE INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r
JOIN permissions p ON p.code IN (
  'dashboard.read',
  'reports.sales',
  'reports.collections',
  'reports.inventory',
  'reports.delivery',
  'reports.performance',
  'system_config.read',
  'system_config.update'
)
WHERE r.code = 'MAIN_OFFICE_AUTHORIZED_USER';

INSERT IGNORE INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r
JOIN permissions p ON p.code IN (
  'dashboard.read',
  'reports.sales',
  'reports.collections',
  'reports.inventory',
  'reports.delivery',
  'reports.performance',
  'system_config.read'
)
WHERE r.code = 'BRANCH_AUTHORIZED_USER';

INSERT IGNORE INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r
JOIN permissions p ON p.code IN (
  'dashboard.read',
  'reports.inventory',
  'reports.delivery'
)
WHERE r.code = 'WAREHOUSE_USER';

INSERT IGNORE INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r
JOIN permissions p ON p.code IN (
  'dashboard.read',
  'reports.sales',
  'reports.collections',
  'reports.performance'
)
WHERE r.code = 'SALES_REP';

INSERT IGNORE INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r
JOIN permissions p ON p.code IN (
  'dashboard.read',
  'reports.delivery',
  'reports.collections'
)
WHERE r.code = 'DELIVERY_PERSON';

INSERT IGNORE INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r
JOIN permissions p ON p.code IN (
  'dashboard.read',
  'reports.sales',
  'reports.collections',
  'reports.inventory',
  'reports.delivery',
  'reports.performance',
  'system_config.read'
)
WHERE r.code = 'OFFICE_USER';

INSERT INTO system_settings (
  `key`,
  value,
  value_type,
  category,
  description,
  is_sensitive
) VALUES
  ('company.default_currency', JSON_QUOTE('LKR'), 'STRING', 'company', 'Default currency code used by reports and dashboards', FALSE),
  ('reports.default_date_range_days', JSON_EXTRACT('30', '$'), 'NUMBER', 'reports', 'Default number of days used by report date filters', FALSE),
  ('inventory.low_stock_notification_enabled', JSON_EXTRACT('true', '$'), 'BOOLEAN', 'inventory', 'Whether low-stock notifications should be generated by background jobs', FALSE),
  ('credit.default_terms_days', JSON_EXTRACT('30', '$'), 'NUMBER', 'credit_control', 'Default customer credit terms in days', FALSE),
  ('offline.sync_retry_limit', JSON_EXTRACT('5', '$'), 'NUMBER', 'offline', 'Maximum retry attempts for queued offline sync items', FALSE),
  ('notifications.email_enabled', JSON_EXTRACT('false', '$'), 'BOOLEAN', 'notifications', 'Email notification sending switch for future email integration', FALSE)
ON DUPLICATE KEY UPDATE
  value = VALUES(value),
  value_type = VALUES(value_type),
  category = VALUES(category),
  description = VALUES(description),
  is_sensitive = VALUES(is_sensitive),
  status = 'ACTIVE';

INSERT INTO audit_logs (
  action,
  entity_type,
  entity_id,
  new_values
) VALUES (
  'PHASE8_REPORTS_DASHBOARD_CONFIG_SEED_APPLIED',
  'system',
  'phase8',
  JSON_OBJECT('modules', JSON_ARRAY('dashboard', 'reports', 'audit_logs', 'system_config'))
);
